version: '3'
services: 
  api:
    image: davidbohl/beerpong-be
    restart: always
    build: .
    command: npm run dev
    ports: 
      - "3000:3000"
    links: 
      - mongo
    depends_on: 
      - mongo 
    volumes: 
      - .:/home/node/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - /beerpong/mongodata:/data/db