version: '3'
services: 
  api:
    image: davidbohl/beerpong-be
    restart: always
    command: node build/server.js
    ports: 
      - "3000:3000"
    links: 
      - mongo
    depends_on: 
      - mongo 
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - /beerpong/mongodata:/data/db