version: '3'
services: 
  app:
    image: davidbohl/beerpong-be
    restart: always
    build: .
    command: bash -c "npm run build && npm run start"
    ports: 
      - "3000:3000"
    links: 
      - mongo
    volumes: 
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - /mongodata:/data/db